# Generated by Django 5.2.4 on 2025-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('autor', models.ManyToManyField(to='api.autor')),
            ],
        ),
    ]
